# Generated by Django 3.1.7 on 2021-03-15 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskID', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=100)),
                ('dueDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('isComplete', models.BooleanField(default=False)),
            ],
        ),
    ]
