# Generated by Django 3.1.7 on 2021-04-17 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calnote', '0002_auto_20210407_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteID', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=256)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
