# Generated by Django 3.1.7 on 2021-04-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calnote', '0003_auto_20210417_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
