# Generated by Django 3.1.7 on 2021-05-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calnote', '0004_auto_20210423_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='noteTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
